# Change these first
owner: redlegdev # Your GitHub organization or username, where this repository lives
repo: fire-crm-upptime # The name of this repository

sites:
  - name: Public Website
    url: https://www.usefireapp.com
  - name: Application
    url: https://app.usefireapp.com
  - name: API
    url: https://api.usefireapp.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.usefireapp.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "FireCRM Platform Uptime and System Status"
  introMessage: >
    Welcome to the FireCRM platform status page.

    This page provides **real-time system status and uptime details** for all FireCRM services, powered by automated monitoring through GitHub Actions and Pages.

    For more information, visit our [GitHub repository](https://github.com/redlegdev/fire-crm-upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
